### PR TITLE
Fix #33, Resolve print format mismatches on 32-bit host

### LINKED ISSUE #33: fails to build under Raspbian and VxWorks
**Describe the bug**
Building elf2cfetbl under Raspbian (the Debian variant released for the popular Raspberry Pi SBC's by the Raspberry Pi organization) it fails with a long laundry list of printf type mismatch errors.

```
/home/pi/cFS/tools/elf2cfetbl/elf2cfetbl.c:2211:67: error: format ‘%ld’ expects argument of type ‘long int’, but argument 5 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
             printf("strstr[%d] = %s; strlenSN = %ld; strlenON = %ld\n",i,strstr(SymbolNames[i], TblFileDef.ObjectName),
                                                                 ~~^
                                                                 %d
```

**To Reproduce**
Build elf2cfetbl under Raspbian.

**Expected behavior**
Should be casting types to what printf expects.

**Code snips**
If applicable, add references to the software.

**System observed on:**
Raspberry Pi Zero W.

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

### PR DESCRIPTION
**Pull request by skliper**
**Describe the contribution**
Casts where needed for print formatting on 32-bit host
Fix #33

**Testing performed**
Steps taken to test the contribution:
1. CI - See https://travis-ci.com/github/skliper/cFS/builds/160575856
2. Also built for vxworks on 32-bit host

**Expected behavior changes**
Builds for vxworks w/ 32-bit host

**System(s) tested on**
 - Hardware: CI, cross compiled for VxWorks 6.9 MCP750 on 32-bit linux host
 - OS: Ubuntu 18.04, VxWorks 6.9, Redhat 6.10
 - Versions: Bundle + this commit

**Additional context**
None (this isn't the only issue on vxworks, but haven't written them up yet)

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
Jacob Hageman - NASA/GSFC

### CODE REVIEW

**Comment by skliper** [comment]
@astrogeco ready for CCB (no label yet)

**Comment by astrogeco** [comment]
> @astrogeco ready for CCB (no label yet)

Thanks for the tag, I added the label

File: elf2cfetbl.c [hunk 1]
```diff
@@ -1895,13 +1895,13 @@ void PrintSectionHeader32(union Elf_Shdr *SectionHeader)
...
 void PrintSectionHeader64(union Elf_Shdr *SectionHeader)
 {
-    if (Verbose) printf("   sh_addr       = 0x%lx\n", SectionHeader->Shdr64.sh_addr);
-    if (Verbose) printf("   sh_offset     = 0x%08lx\n", SectionHeader->Shdr64.sh_offset);
-    if (Verbose) printf("   sh_size       = 0x%08lx\n", SectionHeader->Shdr64.sh_size);
+    if (Verbose) printf("   sh_addr       = 0x%lx\n", (long unsigned int)SectionHeader->Shdr64.sh_addr);
+    if (Verbose) printf("   sh_offset     = 0x%08lx\n", (long unsigned int)SectionHeader->Shdr64.sh_offset);
+    if (Verbose) printf("   sh_size       = 0x%08lx\n", (long unsigned int)SectionHeader->Shdr64.sh_size);
     if (Verbose) printf("   sh_link       = 0x%08x\n", SectionHeader->Shdr64.sh_link);
     if (Verbose) printf("   sh_info       = 0x%08x\n", SectionHeader->Shdr64.sh_info);
```
Comment (jphickey) [inline elf2cfetbl.c:1902]: For instance wouldn't the "sh_link" and "sh_info" need the same cast?  (these are also words of different lengths depending on arch/binary format).

Comment (skliper) [reply elf2cfetbl.c:1902]: Clarified pull request, urgent fix is for vxworks6.9, MCP750.  As you mention, likely requires more casts for other systems but not a certification priority.

Comment (jphickey) [reply elf2cfetbl.c:1902]: How is this related to VxWorks exactly?  The tool runs on the host machine, not on VxWorks.  Are the mismatches specific to running it on a 32-bit host machine vs 64-bit host machine?

**Comment by jphickey** [comment]
With the change of the pull request title change this is even more unclear -- this tool doesn't have anything to do with VxWorks .... this tool is compiled for and runs on the build host no matter what the target OS is.

File: elf2cfetbl.c (hunk 1 above)
Comment (skliper) [reply elf2cfetbl.c:1902]: True enough, this is a 32 bit host.  I only fixed the issues that showed up for the vxworks build on the 32 bit host.  I should have better described the test system.

**Comment by skliper** [comment]
Good point.  Likely an indication of too little time and too much work.

File: elf2cfetbl.c (hunk 1 above)
Comment (jphickey) [reply elf2cfetbl.c:1902]: OK, that makes more sense.  But I'm still not an advocate of just minimally squelching the visible warnings on a specific 32-bit host  (IIRC the machine with the VxWorks 6.9 tools is a 32-bit RHEL 6.x host).  Other compilers/libraries might flag other printfs.  Unless we actually add all the needed casts, warnings are likely reappear again as soon as someone builds on another system.

Comment (skliper) [reply elf2cfetbl.c:1902]: It's a step in the right direction, and removes a cert blocker.  Making it work across compilers/libraries is a very valid open source concern, but not my priority.

**Comment by skliper** [comment]
20200422 CCB - APPROVED
